before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/helm-docs
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - darwin
      - linux
      - windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
- vendor: helm-docs
  homepage: https://github.com/k8s-at-home/helm-docs
  maintainer: k8s-at-home
  description: A tool for automatically generating markdown documentation for helm charts
  license: GNU General Public License v3.0
  formats:
  - deb
  - rpm
  replacements:
    amd64: x86_64
    linux: Linux
